### ISSUE TITLE
Test `config.py` crashes with commands that have no arguments

### ISSUE THREAD

**Issue by karkhaz** [model-checking/cbmc-viewer#135]
The `config.py` script used as a test in the [CBMC starter kit](https://github.com/model-checking/cbmc-starter-kit) crashes when the starter kit includes a Litani job whose command has no arguments.

The crash is on line 80 of `config.py`:
```
cmd, args = job['command'].strip().split(maxsplit=1)
```
A job's command is not guaranteed to have arguments, so the split can fail.

**Comment by tautschnig** [comment]
I am not entirely sure how this relates to cbmc-viewer?
