### ISSUE TITLE
Additional dependencies required on Ubuntu: wheel, pip

### ISSUE THREAD

**Issue by tautschnig** [model-checking/cbmc-viewer#38]
Following the instructions, I initially got the following:
```
$ sudo make install
./setup.py sdist bdist_wheel

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
make: *** [Makefile:32: pip] Error 1
```

Turns out `python3-wheel` is required to have this command available. I then ran into:

```
[...]
cd .. && sudo python3 -m pip install /home/ubuntu/libtpms.git/cbmc/aws-viewer-for-cbmc.git/dist/cbmc_viewer-2.0-py3-none-any.whl
/usr/bin/python3: No module named pip
make: *** [Makefile:56: install] Error 1
```

Once I also installed `python3-pip` it worked just fine.

I'd suggest to append `python3-pip python3-wheel` to `On Ubuntu: sudo apt-get install python3` in `README.md`.

**Comment by markrtuttle** [comment]
On a fresh Ubuntu20 instance, the following commands were sufficient to install the package and to install the package in develop mode:

```
git clone https://github.com/model-checking/cbmc-viewer.git
sudo apt update
sudo apt install python3-pip
sudo apt install python3-venv
make develop
make install
```

And with [this branch](https://github.com/model-checking/cbmc-viewer/pull/117) currently under review, the missing ctags was not an issue.
